### ISSUE TITLE
Can I make my own cold wallet using Sallet One's open source code?

### ISSUE THREAD

**Issue by Bigduckgaga** [SalletOne/sallet-one-cold#3]

**Comment by Bigduckgaga** [comment]
How to do it?

**Comment by SalletOne** [comment]
Yes, if you know Android development, you can download the source code, use android studio, make an apk for your Android device, and install it on your Android device.
If you are not a developer, you can install it on your Android device by downloading the zip from the release.
Please note: To ensure the security of your cold wallet, please use a safe, virus-free, disconnected Android device to install the cold wallet.

**Comment by whisxinyu** [comment]
Whether there are performance requirements for Android phones

**Comment by whisxinyu** [comment]
> Whether there are performance requirements for Android phones

Like the processor。。。。。。
