### ISSUE TITLE
Full-sync switches over to fast-sync on failure

### ISSUE THREAD

**Issue by evanink** [SalletOne/sallet-one-cold#5]
If full-sync fails without having done a flush to disk, it will switch over to fast-sync next time it's started

`[user@work go-ethereum]$ build/bin/geth --syncmode full
INFO [03-02|21:01:36.907] Maximum peer count                       ETH=25 LES=0 total=25
INFO [03-02|21:01:36.908] Starting peer-to-peer node               instance=Geth/v1.9.0-unstable-f9aa1cd2/linux-amd64/go1.11.2
INFO [03-02|21:01:36.908] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB

... panic (my bad)...`

**Comment by SalletOne** [comment]
hey  guys, if you want to fix your ethereum running bugs, please visit ethereum forum.
